version: "3"
services:
  # PostgreSQL database service
  db:
    image: postgres:latest
    container_name: my_postgres_db
    environment:
      POSTGRES_USER: pri
      POSTGRES_PASSWORD: pri
      POSTGRES_DB: pri23
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - mynetwork

  # pgAdmin service
  pgadmin:
    image: dpage/pgadmin4
    container_name: my_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: pri@outlook.com
      PGADMIN_DEFAULT_PASSWORD: pri
    ports:
      - "8080:80"
    depends_on:
      - db

  solr:
    image: solr
    container_name: my_solr
    ports:
     - "8983:8983"
    volumes:
      - data:/var/solr
      - ./startup.sh:/bin/startup.sh
      - ./.env:/bin/.env
      - ./json:/data
    networks:
      - mynetwork

  django:
    build: ./backend
    ports:
     - "8000:8000"
    container_name: pri_django
    volumes:
      - ./backend:/app
    networks:
      - mynetwork
    restart: always

  myvue:
    build: ./frontend
    ports:
     - "3000:3000"
    container_name: pri_vue
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  data:
  pg_data:

networks:
  mynetwork:
    driver: bridge